### PR TITLE
Added plugin_manager

### PR DESCRIPTION
**Pull request by doczi-dominik**
Please reach out if there is anything wrong with my submission. Thanks in advance!

### CODE REVIEW

**Comment by rxi** [comment]
I think you may have mixed up some of your branches with this pull request as it contains the `lfautoinsert` changes. 

Regarding the plugin manager it feels in direct conflict with a lot of the philosophies of lite -- firstly the plugin suggests the user should modify core lua files, which would make upgrading difficult, secondly lite already has a plugin system -- that is, you drop a file in to add a plugin and delete that file to remove it. This system is deliberate and aligns well with lite's goals of simplicity.

**Comment by doczi-dominik** [comment]
Thank you for responding. I also see the problem with modifying the files in core, but I couldn't find another solution.

Regarding the plugins, I just fear that loading all of the plugins in a folder does not align with the _lite_ nature of `lite`. Why would I need to load my golang linter and lua syntax files when I only want to edit shell scripts in `~/.config`.

Maybe I am using `lite` incorrectly. I have a single `~/.lite` directory where the executable and the data folder lies. Should I copy `lite` to every single one of my project directories and symlink my way through every file except the plugins folder? Although if I do that, I can't see the reason for a "project module", if I have to move and edit the config files, I'd just change to "per-project-global" ones!

**Comment by rxi** [comment]
I'd suggest making a `data/user/plugins` folder, if you put plugins in here they won't be loaded by the plugin system automatically. You can then do `require "user.plugins.<plugin_name>"` to explicitly load a given plugin either in your `data/user/init.lua` file or the `.lite_project.lua` file in your project's directory

**Comment by doczi-dominik** [comment]
Oh, that is a really nice solution! The only problem that still remains is loading plugins on-the-fly (which may sometimes be useful), but I can overlook that as it IS rare. Thanks again!

Sidenote: `lite` is now my favorite editor, and I really like it's approach to speed and extensibility. Hopefully it catches on and there'll be support for more languages and maybe language servers/linters - since it is optional, I think it would be fine. :)

**Comment by rxi** [comment]
Regarding loading in plugins on-the-fly (that is, loading them once rather than reloading them) the `core:reload-module` command can be used to load a plugin by its module name (eg. `user.plugins.<plugin_name>`), this will work though it might be not be obvious as only currently-loaded modules are shown in the suggestions

**Pull request closed without merging**
