### PR TITLE
add new plugins (eofnewline)

### PR DESCRIPTION
**Pull request by bokunodev**
Iwant to submit my plugins.

### CODE REVIEW

**Comment by SwissalpS** [comment]
Thanks, I've been thinking of this too.

**Comment by SwissalpS** [comment]
It does not seem ok to manipulate DocView.lines table directly. It was causing crashes this way.
Try something like this:
```
local core = require "core"
local command = require "core.command"
local Doc = require "core.doc"
require "string"

local function eof_newline(doc)
	local eofl = #doc.lines
	for i = eofl, 1, -1 do
		if string.match(doc.lines[i], "^%s*$") then
			doc:remove(i, 1, i + 1, math.huge)
		else
			break
		end
	end
	eofl = #doc.lines
	if "\n" ~= doc.lines[eofl] then
		doc:insert(eofl, math.huge, "\n")
	end
end

command.add("core.docview", {
  ["eof-newline:eof-newline"] = function()
    eof_newline(core.active_view.doc)
  end,
})

local save = Doc.save
Doc.save = function(self, ...)
  eof_newline(self)
  save(self, ...)
end
```

**Comment by bokunodev** [comment]
thanks, now `Doc.lines` arent modified directly and loop function call are removed except `string.match`.

**Comment by SwissalpS** [comment]
please put eofnewline in alphabetically, above eval plugin (on the plugins list)

**Comment by rxi** [comment]
Looks good! Thanks

**Pull request merged**
