### PR TITLE
toggle whitespace visibility during runtime

### PR DESCRIPTION
**Pull request by SwissalpS**
requested by @stefanos82 in issue #37

### CODE REVIEW

**Comment by rxi** [comment]
Would you mind changing the commands from `yes` / `no` to `enable` / `disable`, and set `visible` to `true` by default? Otherwise looks great!

**Comment by SwissalpS** [comment]
thanks :D

**Comment by rxi** [comment]
Changes look good! You're right about the config, I'd suggest `config.draw_whitespace = true` as a name and a default. Do you want to make this change too before I merge?

**Comment by SwissalpS** [comment]
> ...want to make this change too before I merge?

Sure, done :)

**Comment by rxi** [comment]
Looks good, but I think you might have accidentally reverted the command names!

**Comment by SwissalpS** [comment]
good catch, thanks.

**Pull request merged**
