### PR TITLE
Propose scale status

### PR DESCRIPTION
**Pull request by SwissalpS**
adds getter method to scale.lua
adds scalestatus.lua which displays current scale in status-view

### CODE REVIEW

**Comment by rxi** [comment]
Looks good, you need to wrap the following in `pcall` if you want to handle the failure case:
```lua
local scale = require "plugins.scale"
```
Instead, though, it's probably better to call the `require` function directly as opposed to trying to "handle" the error yourself -- in the case `scale` is not installed the `scalestatus` plugin will stop loading and lite will automatically produce an error and display the log to the user once all the other plugins have loaded. This is the intended behaviour for unresolved plugin dependencies.

**Comment by SwissalpS** [comment]
Yes, if scale is not installed, the check for scale.get_scale is not performed.
The loading mechanism warns in log.

The current check only checks if the version supports get_scale method.
If not, it aborts loading scalestatus and informs in log about need for update.

I felt this was the intended way to go, and I understand you to confirm this.

**Comment by rxi** [comment]
In terms of the code this makes sense, though at a glance it seems I may have been confused by the first part of the comment:
```lua
-- make sure plugin is installed and has get_scale field
```

-----

> Edit: This situation asks for a unified way for plugins to expose their version
> since not all functions can be tested as easily as it is in this situation.

This isn't something that will be enforced. Even the check you're doing is not something I would personally perform; all `lite` plugins assume all other plugins are the latest version, and that the latest release version of lite is being used. In the case of a plugin not working after updating something the first call of action should be to assure everything is on the latest version. That being said you're welcome to add a `version` field on the module of any plugins you author.

Thanks!

**Comment by SwissalpS** [comment]
Thanks for the clarification and merge :D

**Pull request merged**
