### PR TITLE
Batch File Language Plugin

### PR DESCRIPTION
**Pull request by liqube**
Handle all essentials in .bat and .cmd files.

Three important features I've been missing from lite so far in parsers:
1) A way to stop parsing at a certain rule
2) Caseless file extension matching (Windows)
3) Caseless syntax matching (especially noticable in batch files, where many use all uppercase syntax)

### CODE REVIEW

**Comment by liqube** [comment]
Looks like this:
snap20200517225622

**Comment by liqube** [comment]
Missing caseless matching becomes clear when you encounter batch files like this (I edited the first one):
snap20200517225738

**Comment by rxi** [comment]
Looks good! Regarding the caseless symbol matching, there are two options: 

Programmatically iterate a list of the keywords and add both the lowercase and uppercase variants (using `string.upper()`) to the keywords table.

Or, if you want true case-insensitive matching you could instead add a metatable to the symbol table:
```lua
local case_insensitive = {
  __index = function(t, k)
    return rawget(t, k:lower())
  end
}

-------------------------------------------

  symbols = setmetatable({
    ["if"]  = "keyword",
    -- ...
  }, case_insensitive)

```

**Comment by liqube** [comment]
> 
> 
> Looks good! Regarding the caseless symbol matching, there are two options:
> 
> Programmatically iterate a list of the keywords and add both the lowercase and uppercase variants (using `string.upper()`) to the keywords table.
> 
> Or, if you want true case-insensitive matching you could instead add a metatable to the symbol table:
> 
> ```lua
> local case_insensitive = {
>   __index = function(t, k)
>     return rawget(t, k:lower())
>   end
> }
> 
> -------------------------------------------
> 
>   symbols = setmetatable({
>     ["if"]  = "keyword",
>     -- ...
>   }, case_insensitive)
> ```

Ah, good to know. Still getting the hang of advanced Lua here, meta tables and such.

I opted for the duplicating entries solution as it's sufficient and probably even more relevant, because you wouldn't want to support users writing commands like "eChO".

This should be ready now, uppercase sample attached.

snap20200518173817

**Comment by liqube** [comment]
I clearly have some learning to do on here. Please ignore my proceedings, this is good to be merged 🤣

**Comment by rxi** [comment]
Thanks!

**Comment by rxi** [comment]
Regarding the stop-parsing-at-a-certain-rule, I assume for the `eof`, one possible solution would be to treat `eof` like you would the start of a string or multi-line comment, and use an unmatchable pattern to close it:
```lua
    { pattern = { ":eof", "%z" },       type = "comment"  },
```
This would highlight the `:eof` and everything after it as a comment

**Comment by liqube** [comment]
> 
> 
> Regarding the stop-parsing-at-a-certain-rule, I assume for the `eof`, one possible solution would be to treat `eof` like you would the start of a string or multi-line comment, and use an unmatchable pattern to close it:
> 
> ```lua
>     { pattern = { ":eof", "%z" },       type = "comment"  },
> ```
> 
> This would highlight the `:eof` and everything after it as a comment

I see what you mean, but I can't seem to get this to work so far. Will have to look into it more. I believe some other rule might interfering with it. If I move it higher up I get nothing on "goto :eof", and highlighting of the rest of the text following after ":eof" on "goto:eof" (no space).

**Pull request merged**
