### PR TITLE
language_glsl and language_hlsl plugins

### PR DESCRIPTION
**Pull request by alexGuntha**
Added syntax highlighters language_glsl.lua for glsl files (there is no standard extension for glsl files, so it considers the commonly used extensions ".glsl", ".vert" and ".frag" as glsl files) and language_hlsl.lua for hlsl files (.hlsl), and inserted their description in README.md.

One additional feature that is mainly useful for myself (since I frequently edit shaders in both languages) and can maybe be useful to others is that it also highlights some commonly-used HLSL keywords in GLSL files, and the other way around, in bright red, so the user can easily detect the usage of a built-in function or type that doesn't exist in the language he is currently writing in.

See example in gif (copy-pasting a line from an hlsl file to a glsl file)
hlsl_glsl_lite

### CODE REVIEW

**Comment by rxi** [comment]
Unfortunately adding custom colors into `style` from a plugin like this ends up problematic when other color themes are used, the `forbiddenbuiltins` feels almost like a misuse of the syntax highlighting system too -- such functionality might work better as a plugin (see the `spellcheck` or `linter` plugins).

I'd be happy to merge if the `forbiddenbuiltins` and style color changes were removed. Thanks!

**Comment by alexGuntha** [comment]
All right, I removed the "common mistake detection" feature (I'll look into how to make it as separate plugins later) and the style changes; now built-in functions are highlighted as ```"keyword"```s

**Comment by rxi** [comment]
Looks good! Just noticed the text on the README's table entries needs fixing too -- both are still listed as `language_cpp`

**Comment by alexGuntha** [comment]
Oops you're right, that is now fixed.

**Comment by rxi** [comment]
Thanks!

**Pull request merged**
