### PR TITLE
Markers plugin

### PR DESCRIPTION
**Pull request by petrihakkinen**
Plugin for placing markers to documents and jumping quickly between them.

ctrl+f2 = place marker
f2 = jump to next marker

### CODE REVIEW

**Comment by rxi** [comment]
Looks good! There are some changes I'm considering on the core for the future which would allow plugins like this to keep the markers in the correct positions as lines are added and removed, something I assume you likely looked into and resolved that there was not a good way to handle.

One minor issue is that due to some changes to `DocView:draw_line_gutter()` the x-offset of the marker won't draw in the correct position on the master version (or the next release) -- the `x` value now corresponds to the far-left-edge of the gutter rather than the text offset. This is a simple change, though:
```lua
function DocView:draw_line_gutter(idx, x, y)
  if markers[self.doc] and markers[self.doc][idx] then
    local h = self:get_line_height()
    renderer.draw_rect(x, y, style.padding.x * 0.4, h, style.selection)
  end
  draw_line_gutter(self, idx, x, y)
end
```
The above also changes the mark rectangle a little to fit in a way I feel is more inline with lite's general look.

**Comment by petrihakkinen** [comment]
Yes, moving the markers as text is edited looked a bit problematic so I didn't really attempt it. I agree it would make the plugin much more user friendly.

Looking at the code it would seem that hooking to `Doc:insert` and `Doc:remove` would work but undo/redo would be more difficult. What kind of changes to the core have you thought?

**Comment by rxi** [comment]
I've been experimenting with exposing the internal insert/remove functions which are called by insert/remove/undo/redo, and been using your plugin as a means to test if hooking into them is a reasonable enough approach -- it seems to be working well and isn't *too* ugly:

```lua
local function shift_lines(doc, at, diff)
  if diff == 0 then return end
  local t = {}
  for line in pairs(cache[doc]) do
    line = line >= at and line + diff or line
    t[line] = true
  end
  cache[doc] = t
end


local raw_insert = Doc.raw_insert

function Doc:raw_insert(line, col, text, ...)
  raw_insert(self, line, col, text, ...)
  local line_count = 0
  for _ in text:gmatch("\n") do
    line_count = line_count + 1
  end
  shift_lines(self, line, line_count)
end


local raw_remove = Doc.raw_remove

function Doc:raw_remove(line1, col1, line2, col2, ...)
  raw_remove(self, line1, col1, line2, col2, ...)
  shift_lines(self, line2, line1 - line2)
end
``` 

It will leave the plugin in an odd state until the release as it won't work right unless the master branch version of `lite` is used, once I commit to the raw_insert/raw_remove changes I can submit a pull request to your repo, or accept *this* pull request in its current form and make the changes myself a little bit later.

This specific plugin opened up the idea of wanting to rework some of lite's internals to better support the kind of things it's trying to achieve, thus it hasn't been as simple as merging it immediately.

**Comment by petrihakkinen** [comment]
Looks good to me! Sounds like it would be less hassle if I handover the plugin to you at this point so you can do the changes you deem necessary and sync them with the next release. Feel free to make any changes to it. Would this be okay with you?

**Comment by rxi** [comment]
@petrihakkinen That sounds great, I'd happy to do it. I can let you know when everything is up if you'd like

**Comment by petrihakkinen** [comment]
Sure, thanks!

**Comment by rxi** [comment]
Pushed the updated version!

**Comment by liqube** [comment]
very cool one, thanks :)

**Pull request closed without merging**
