### PR TITLE
Implemented a todo annotations viewer plugin.

### PR DESCRIPTION
**Pull request by drmargarido**
Allows for visualization grouped by files or by annotation type.

### CODE REVIEW

**Comment by rxi** [comment]
Very cool! One minor improvement would be to change the thread that updates the table to write to a temporary table then set it at the end, this will get rid of the flicker when it tries to display the table while it's being rebuilt.

I noticed the icon used in the "tag" grouping mode for an expanded group is also wrong.

If you're happy fixing these I can merge it in once it's done.

**Comment by drmargarido** [comment]
Thanks for the feedback. Yes, I will fix those.

**Comment by drmargarido** [comment]
Updated with the fixes.

**Comment by rxi** [comment]
Another bug I stumbled upon: Deleting a file from the project seems to cause a crash

**Comment by drmargarido** [comment]
I fixed that some time ago. I force pushed and updated the commit, are you on the last version?

**Comment by rxi** [comment]
If [this is the latest version](https://raw.githubusercontent.com/rxi/lite-plugins/a05a37595f12c8fb1ffe3859805f73d76cefef03/todotreeview.lua) then yes

**Comment by drmargarido** [comment]
Yes, that's the last version. Hum, I will try to reproduce it.

**Comment by drmargarido** [comment]
Fixed the crash when deleting a file from the project.

**Comment by rxi** [comment]
After a little consideration, I'm thinking that for larger plugins such as this one it will likely make more sense that they're kept in the author's repo so that the author can take responsibility of maintaining the plugin more directly. If you're happy with that arrangement would you be able to make a repo for your plugin, then make a pull request updating the table on this repo's `README.md` to link to your plugin's repo *(similar to what is done with the `theme16` plugin)*?

Thanks!

**Comment by drmargarido** [comment]
Sure, I will create the repository.

**Comment by drmargarido** [comment]
Created the separated repository and updated the readme.

**Comment by rxi** [comment]
Thanks!

**Pull request merged**
