### PR TITLE
check if file handle actually exists

### LINKED ISSUE #100: [bug] nil value fp when using plugin last project
An error occurs  that shows up in the logs that fp is a nil value when using the lastproject.lua plugin, this has occured no matter whether if i open the progrom with an argument or not, here is a snippet:

lite error

i run Manjaro linux, 64 bit, kindly do review this, it would be such a handy feature to use, at the moment i have resulted to deleting the plugin entirely, sorry but i don't quite have sufficient knowledge in Lua nor C for that matter, kindly do resolve this, it would be such a handy feature to have, and also great text editor u've made here, i'm definitely looking forward to maining it ☺️, good work 👌

### PR DESCRIPTION
**Pull request by SwissalpS**
should fix #100

### CODE REVIEW

**Comment by quadroli** [comment]
How bro?
(In lay man terms please)

**Comment by SwissalpS** [comment]
By checking if fp is not nil. The PR-diff shows what I changed to do so.

**Comment by quadroli** [comment]
fp is nil, straight from the error message, and the file am tryna open definitely does exist

**Comment by SwissalpS** [comment]
interesting. I also assume the directory is on local machine and you have permission to write to it.
Does the variable `last_project_filename` contain a valid string?

You should be able to check that by inserting a line before L16 `core.log('last_project_filename: ' .. dump(last_project_filename))`

**Comment by quadroli** [comment]
New error: cannot get undefined variable dump at usr/share/lite/core/init.lua:314

**Comment by SwissalpS** [comment]
you can use `print(tostring(last_project_filename))` then the output should be in the terminal you launched lite from.

yes, the location is fine. Generally you want to debug output before the variable is used and causes a crash.

**Comment by quadroli** [comment]
so, these are the error messages i get having included both that log line and the print line immediately after:

lite last project error

oddly enough, this time it doesn't raise any errors about about dump being undefined whatsoever,

and also, the output i get from my terminal due to that print statement is:
/usr/bin/.lite_last_project
but when i search for this file, its seems  to be non_existent and not because it happens to be a hidden file to.

**Comment by quadroli** [comment]
ok, leave all the mambo jambo i just sent, it was due to file corruption had some buffers created accidentally, so, still, the print statement gives me this: /usr/bin/.lite_last_project

and, including the core.log line still tells me undefined variable dump

removing dump from the log line, i still get fp is null

**Comment by quadroli** [comment]
so sorry dude for this long journey, i finally used the version from the pull request and the error messages stopped, 
and i've finally seen where the log is meant to be shown, at the bottom left over there,same place saved shows up from,
 but i think cause of where my files are located, it seems as if it just ends up loading this folder by default every time whenever no argument is provided 

Screenshot from 2020-11-24 20-35-06

but anyways dude, thanks for the feedback and all was real informative

**Comment by SwissalpS** [comment]
/usr/bin should not be write-able location

If I feel motivated, I may take a closer look at this. It's kinda fighting the general way most cli launched editors work: `lite path/to/file`

workspace plugin mostly covers my needs (as long as my pc does not freeze/crash). I use lite for multiple projects, so a last-project system does not fit into my workflow.

Thanks for the information, it will be useful to whoever attacks the problem.

**Comment by quadroli** [comment]
very welcome 👍 to whoever may tackle the problem

**Pull request merged**
