### PR TITLE
Added changesyntax, cutcopyline, drawwhitespace, selectionhighlight, and opensettings plugins.

### PR DESCRIPTION
**Pull request by luveti**

### CODE REVIEW

**Comment by rxi** [comment]
Quite a few there, looking good!

A couple of points from skimming over it which are worth fixing:
* Plugin commands should all use the form: `plugin-name:command-name` (eg. `core:open-settings` should be `open-settings:open-settings` or `open-settings:open`)
* The `command.add` call should pass `"core.docview"` as its first argument if it requires a `DocView` to be the active view to work (`changesyntax.lua`, `cutcopyline.lua`)
* You can get a `DocView`'s line directly from `self.doc.lines[line_number]`, where `self` is the `DocView`
* Any value from `core.style` or `core.config` shouldn't be cached (eg. the caching of the whitespace color in `drawwhitespace.lua`) as `lite` would require a restart if the value was change after startup
* If you want to allow the possibility for "unofficial" style colors, you can do `local color = style.my_custom_color or style.selection` to use the custom color in the case the style supports it or fall back to one of the "standard" colors

Lastly if you're looking to maintain the plugins yourself or plan to make more and would rather retain control over them: make a repo for the plugins then make a pull request to *update only the table* with entries which link to the raw plugin in your own repo (append `?raw=1` to the end of the file link) -- if you'd rather the plugins live in this repo that's fine too!

Thanks!

**Comment by rxi** [comment]
Hopefully not to be too annoying: would you be able to let me know what you plan to do? I'm liking the plugins you've made (getting some good usage out of the selection one) -- if the changes aren't something you intend to make I'll likely merge the pull request as is at some point and make the changes myself.

No rush if it is something you plan to do yourself, or if you want to move the plugins to another repo -- just trying to get an idea of how to proceed with it! Thanks!

**Comment by luveti** [comment]
Hey @rxi. Sorry I haven't gotten a chance to perform the requested changes just yet. I ran into an issue with lite and decided to continue using vscode until I had time to investigate it more and open an new issue.

I plan on moving the plugins to my own repo as I intend to create many more! I'll do that sometime this week. Feel free to snag the `selectionhighlight` plugin and place it into this repo though if you'd like it here!

**Comment by rxi** [comment]
Not a problem at all! Don't hesitate to open an issue even if you're not entirely sure what the cause of the problem is -- it can be expanded on later.

Thanks for the okay on the `selectionhighlight` plugin -- would you be alright with me stealing the `drawwhitespace` plugin from you too and popping it in this repo? Afterwards I'll close this pull request. I hope you get the chance to update the table with links to your external-repo plugins once everything is set up; I'm enjoying the functionality that's been added to `lite` from the ones you've already written and I'm interested in seeing what you come up with if you end up making any more!

**Comment by luveti** [comment]
Thanks! Extending this editor has been very enjoyable and much simpler compared to others I've wrote plugins for!

You're more than welcome to take whatever you want from this pull request. I'll place the remaining plugins in a new repo when I get time.

**Comment by rxi** [comment]
Aces; thanks

**Pull request closed without merging**
