### PR TITLE
Add basic makefile syntax highlighting

### PR DESCRIPTION
**Pull request by pta2002**
I think this should be fairly helpful for folks dealing with Makefiles, was actually surprised to see it's not already supported.

Let me know if anything is wrong/needs to be fixed up.

### CODE REVIEW

**Comment by rxi** [comment]
Looks good, if you don't mind adding it to the table in README file I'd be happy to merge!

> Note: if you make a pull request, the table should be updated and kept in alphabetical order...

Thanks!

**Comment by pta2002** [comment]
Oh I thought I had added it, I'll check this though!

**Comment by pta2002** [comment]
Oops looks like I had it on the wrong branch, this should do it

**Comment by rxi** [comment]
Looks good! Thanks

**Pull request merged**
